### PR TITLE
Layout issues for roundinfo

### PR DESCRIPTION
**Pull request by ryancreatescopy**
WIP fixes on #95 

@samajammin @wackerow need some help adding the round totals together...

image
It currently just puts the numbers one after the other...

Fixed the duplicate round status in #95 (pictured below) in #107 
image

### CODE REVIEW

**Comment by pettinarip** [comment]
Fixed.

image

I've used the `fixednumber.addUnsafe` method to add the FixedNumbers. Docs: https://docs.ethers.io/v5/api/utils/fixednumber/#FixedNumber--methods

Bonus:
- Small refactor: I moved the methods and calculated values to keep them grouped so that it's easier to find them.

**Comment by samajammin** [comment]
Awesome, thanks @pettinarip! @ryancreatescopy mind taking a look at Pablo's changing & seeing if there's anything else needed on this PR?

**Comment by ryancreatescopy** [comment]
Thanks @pettinarip – everything here looks great assuming that you left the following error because it's being addressed in #107 

image

**Comment by pettinarip** [comment]
Sorry, I thought this PR was just to fix the number format but now I've noticed that in the issue description there were 2 other things to be fixed. Will fix them now since I was just starting to work on a different ticket.

**Comment by ryancreatescopy** [comment]
> Sorry, I thought this PR was just to fix the number format but now I've noticed that in the issue description there were 2 other things to be fixed. Will fix them now since I was just starting to work on a different ticket.

No worries @pettinarip it looks as if the round total not adding up correctly has been fixed either way! Double check #107 before working on the other fix as I think that's been done too!

**Comment by pettinarip** [comment]
@ryancreatescopy I can confirm that:
1. The "time left to reallocate" issue is fixed in #107
2. Regarding the issue description in #95, this PR still needs to address the `Legends shouldn't pluralise if 1 contibutor.` error. Will work on that.

**Comment by ryancreatescopy** [comment]
> 2\. Regarding the issue description in #95, this PR still needs to address the `Legends shouldn't pluralise if 1 contibutor.` error. Will work on that.

Awesome, thanks Pablo!

**Comment by pettinarip** [comment]
@ryancreatescopy I just merged that last thing. I think that should be all for this PR.

**Review by samajammin — APPROVED** [review]
👍

**Pull request merged**
