### PR TITLE
Refactor: maxRecipients getter

### PR DESCRIPTION
**Pull request by pettinarip**
When there is no `currentRound`, default the `maxRecipients` value to the one that the MACI factory has. Refactor #491

### CODE REVIEW

**Review by samajammin — APPROVED** [review]
Looks great! Added a small commit - there was one missing getter to refactor.

One thought - we should probably also merge this PR into `develop` so this can be synced upstream in the monorepo (the `staking-round` branch is being kept separate. Mind doing that as well?

**Comment by pettinarip** [comment]
Thanks for the review. Ok, I will merge **this** PR into develop first because I was planning in merging develop into the `staking-round` branch since I have this other PR open https://github.com/ethereum/clrfund/pull/504

**Comment by pettinarip** [comment]
> Thanks for the review. Ok, I will merge **this** PR into develop first because I was planning in merging develop into the `staking-round` branch since I have this other PR open #504

Not a good idea Pablo. I'll do what Sam just said.

**Comment by samajammin** [comment]
Lol ya I'm guessing you branched off `staking-round` to create this? We may just have to cherry pick these commits.

**Comment by pettinarip** [comment]
> Lol ya I'm guessing you branched off `staking-round` to create this? We may just have to cherry pick these commits.

Exactly

**Pull request merged**
