### PR TITLE
Hero Banner styling issue with Timer

### LINKED ISSUE #272: Hero Banner styling issue with Timer
Fix styling for the timer in the hero banner.

### PR DESCRIPTION
**Pull request by corwintines**
Fixes: https://github.com/ethereum/clrfund/issues/272

### CODE REVIEW

**Comment by samajammin** [comment]
This looks good 👍 

What are your thoughts on the mobile display?
clr fund - clr fund 2021-08-18 at 8 53 23 PM

Not a strong opinion but feels kind of weird to be center aligned while everything else is left aligned.

Perhaps we should display the timer above the button & have it left aligned like the rest of the content?

Open to ideas here...

**Comment by pettinarip** [comment]
Not a strong opinion either.

> Perhaps we should display the timer above the button & have it left aligned like the rest of the content?

Agreed with that. Would be more consistent with the rest of the content we have.

**Comment by corwintines** [comment]
Note: In scrum we decided that we would put the timer above the button, and left align it.

**Comment by samajammin** [comment]
@corwintines I think there was a bit of miscommunication here. I was only talking about the mobile layout - I think we should keep the desktop layout as is:
clr fund - clr fund 2021-08-19 at 1 41 18 PM

Now it looks too tall with everything stacked IMO:
clr fund - clr fund 2021-08-19 at 1 42 45 PM

**Comment by samajammin** [comment]
I'll just make these changes real quick 😄

**Review by samajammin — APPROVED** [review]

**Pull request merged**
