### PR TITLE
No ability to exit out of MatchingFundsModal

### LINKED ISSUE #249: No ability to exit out of MatchingFundsModal
Clicked to "Add funds" to the matching pool:

Image 2021-08-10 at 12 55 02 PM

Modal should be closable, same UI as WalletModal component.

### PR DESCRIPTION
**Pull request by corwintines**
https://github.com/ethereum/clrfund/issues/249

### CODE REVIEW

**Review by pettinarip — CHANGES_REQUESTED** [review]
@corwintines One thing I noticed is that if the user is not connected, the "connect" button is centered, while this style is not consistent with the rest of the modals we have.

Also, when you are connected, you will see a different pattern, a Cancel and a Submit button.
image

I would say, lets remove the close icon and lets use a Cancel button. That way we are going to have the Connect button in one side and the Cancel in the other.

**Comment by corwintines** [comment]
> @corwintines One thing I noticed is that if the user is not connected, the "connect" button is centered, while this style is not consistent with the rest of the modals we have.
> 
> Also, when you are connected, you will see a different pattern, a Cancel and a Submit button.
> image
> 
> I would say, lets remove the close icon and lets use a Cancel button. That way we are going to have the Connect button in one side and the Cancel in the other.

Sure. The reason I hadnt done that is the connect button and the cancel button have different heights in their styling. I can play around with it, but then it also wouldnt be consistent.

**Comment by pettinarip** [comment]
Uhmm yes, I know that (now deleted) `ConnectionModal` used those two buttons. Maybe you can check the styles were used there.

**Comment by pettinarip** [comment]
@corwintines this got me thinking whether we would want to make the Connect button consistent with the rest of the buttons we have. Perhaps it is worth verifying if the Connect button is the only button with a smaller size. If that is correct, then I would support the idea of changing its size.

**Comment by corwintines** [comment]
Closing and will redo with new functionality discussed in discord around popping up walletmodal immediately

**Pull request closed without merging**
