### PR TITLE
Display correct cart total [Fixes #152]

### LINKED ISSUE #152: Displaying wrong total after Contribution Phase
Currently the cart total for the contribution phase is correct, it is summing up the cart, and displaying the total. 

Reallocation phase onwards it is showing the wrong total though. Currently, it is summing up the committedCart item amounts. This works fine unless there is a reallocation that takes place where there is not a full reallocation and some goes to the cart. Ex:
- User contributed 100 DAI, 50 DAI to 2 projects in contribution phase
- Total shows 100 DAI because that is the committedCart sum. This is correct here. 
- User Reallocates funds. 45 DAI to 2 projects, and submits the reallocation. This would mean there is 10 DAI going to matching pool
- Total shows 90 DAI now, when it should still show 100 DAI

To fix this, need to return in the getTotal function currentRound.contribution in Cart.vue. This will show the total contribution which will include all cases of reallocation where the full amount wasnt reallocated to projects and has a matching pool amount.

### PR DESCRIPTION
**Pull request by samajammin**
I _believe_ this fixes #152

### CODE REVIEW

**Comment by samajammin** [comment]
@corwintines please check my logic here...

Maybe I'm missing the purpose of `getTotal` - don't we always want to display the current total of the cart (vs. just returning the committed contribution amount via `this.$store.state.contribution`)? Not sure I follow the previous logic.

In any case, this now seems to display the correct cart total & warnings when reallocating.

**Review by corwintines — COMMENTED** [review]
getTotal was used to get the total for that bottom total, which needs to include the contribution amount for when the user may have reallocated and now has some matching pool funds. If we just do cart total, then we miss out on matching funds.
Screen Shot 2021-06-21 at 12 53 27 PM
 Ill add a change here that should fix it, but if you don't agree with it let me know and we can change it some more.

**Comment by corwintines** [comment]
@samajammin I added some changes to use the getCartTotal in applicable places and restored the getTotal functionality from before .
Screen Shot 2021-06-21 at 1 07 57 PM

I believe this is what we are going for.

**Comment by corwintines** [comment]
I guess for some context. I broke out the getCartTotal to be how we total up the cart, and used the getTotal to show the total you either will or have contributed.

**Comment by samajammin** [comment]
Nice - thanks!

**Pull request merged**
