### PR TITLE
Adds `e.preventDefault()` to forms [Fixes #367]

### LINKED ISSUE #367: Forms refreshing page on "enter/return"
`CartItems.vue`, `MatchingFundsModal.vue` and `Join.vue`

These components use forms that do not utilize `preventDefault()` when form is submitted. They are wired to use a separate button to handle the submission, but if a users cursor is in the input field and they press "enter/return" it will trigger a form submission and refresh the page by default.

### PR DESCRIPTION
**Pull request by wackerow**
Forms within `CartItems.vue`, `MatchingFundsModal.vue` and `Join.vue` components do not have explicit @submit handlers, causing the default action to refresh the page if a user pressed "enter/return" while in the form input.

- Adds `@submit="(e)=>{e.preventDefault()}"` to `<form>` elements

Submission still accomplished via a specified button.

### CODE REVIEW

**Review by pettinarip — APPROVED** [review]
Good catch. I'm wondering if we just want to remove the `form`s and replace them with a `div` since we are not using them as forms. Also because I don't feel ok leaving those `e.preventDefault()` there.

**Review by corwintines — COMMENTED** [review]
I agree with @pettinarip here, is there a reason to leave these as a form? This does fix the problem, but I agree that we could probably just get away wtih converting the forms to divs

**Comment by samajammin** [comment]
I agree re: removing the forms entirely, as long as we're sure that the Vue validation libraries & whatnot will work fine without them.

**Comment by corwintines** [comment]
> I agree re: removing the forms entirely, as long as we're sure that the Vue validation libraries & whatnot will work fine without them.

I dont think it should since I think its on the input level, but will test a bit more extensively for this

**Review by corwintines — APPROVED** [review]

**Pull request merged**
