### PR TITLE
MobileTabs / Cart

### LINKED ISSUE #52: Scroll position not resetting to top w/ internal links
On mobile, noted that scrolling down a page, then tapping an internal link, does not refresh the the scroll position to top when the new view loads:
image
image

### LINKED ISSUE #72: Cart layout
When the cart is open the layout at the top should be like this to preserve vertical scroll space.

image

### LINKED ISSUE #80: Cart CTA hover bug
Hovering on the cart button shouldn't clip the left edge like it does right now...
https://user-images.githubusercontent.com/40891631/119320670-bc384f80-bc73-11eb-84eb-9b434ceb4bc1.mov

It should behave more like this... however also shouldn't force project list content over
https://user-images.githubusercontent.com/40891631/119320719-c78b7b00-bc73-11eb-9563-9e32c9ff0285.mov

### PR DESCRIPTION
**Pull request by wackerow**
Lays out a mobile nav bar, to prep for improving cart functionality.

Cart currently being displayed and managed through the NavBar component, and this will need to be moved (possibly into the App component) to keep track of what the active app state is, and what view should be shown on mobile (Round vs Projects vs Cart). Perhaps this could be done with routing parameters, will discuss at standup. 

**TODO**
- [x] Discuss round information layout for M-L screens w/ @ryancreatescopy - do we hide? do we display as a banner on top?
- [x] Cart panel should be sticky (100vh - nav) -- using `fixed` positioning instead
- [x] Cart header - fix to top
- [x] Cart header - update "remove all" to dropdown menu
- [x] Total bar - fix to bottom
- [x] Cart items section - scrollable on overflow 
- [ ] ...with BrightID at bottom

### CODE REVIEW

**Comment by samajammin** [comment]
@wackerow I think generally the layout/UI for mobile & desktop are looking really solid!

Functionality-wise I'm getting a bunch of errors & unable to view items in my cart after adding them:
Image 2021-05-21 at 5 20 45 PM

Let's debug on Monday 👍

**Comment by wackerow** [comment]
@samajammin Yeah, couple booleans got left flipped.
In `Cart.vue`, changing these two back to:
```
  contributionPhase = true
  reallocationPhase = false
```
should get the cart to at least load right now, but yes, I'm down to sync more on this on Monday.

**Comment by ryancreatescopy** [comment]
image
Round Info is now squashed

image=
Tooltips are cut off

image
RoundInfo overhangs component edge

**Review by samajammin — APPROVED** [review]
Merging after some cleanup commits. Nice work @wackerow! 👍

**Pull request merged**
