### PR TITLE
Fix link section form validation

### PR DESCRIPTION
**Pull request by samajammin**
Update to use computed property to check if section is valid.

### CODE REVIEW

**Comment by wackerow** [comment]
@samajammin Pushed a patch to get the build passing.

This seems to work on testing where it recognizes a valid entry before leaving the field, but...
I am still getting the red error message on load:
image
And doesn't wait til first blur to validate:
https://share.getcloudapp.com/RBuYnQXe

**Comment by samajammin** [comment]
Good catch @wackerow - ya that will need a different validation check 🤔

**Comment by samajammin** [comment]
Easiest solution is to just remove that error class on the section. I updated it to this, let me know what you think @wackerow @ryancreatescopy:
Image 2021-05-06 at 2 30 51 PM

I think this is fine as each individual input still has validation & warning prompts.

**Comment by ryancreatescopy** [comment]
As far as I can tell, this fixes the issue of having to tab out the input to press "next".

However it doesn't add the atBlur validation... was this PR meant to fix this?

@sam I think your solution pictured above is fine!

**Comment by Ely68** [comment]
merged

**Pull request merged**
