### PR TITLE
Adding getters and status to project card/page

### LINKED ISSUE #74: Remove register button from projectCard / projectPage
If admins are going to be approving/registering projects from `recipients` we don't need a register button on the projectCards/projectPage
- [x] remove "register" button from project page & ProjectListItem component

Only registered projects should be visible in the projectList... 
- [x] confirm we only list registered projects

NOTE: they should still have a url so that admins can review their page before registering them... Maybe this means we should retain the button on the ProjectPage...

### LINKED ISSUE #75: Remove input / contribute CTA from projectCard / projectPage when necessary
if user has contributed:
- when reallocation phase is over this is no longer necessary

if user hasn't contributed:
- after contribution phase, this CTA is no longer necessary

if user is unconnected and it's during the reallocation phase:
- show the CTA in case they have contributed. 
- pressing the CTA should trigger the wallet connection
- once they're connected we can detect an if they never contributed we can display an error message in a modal

Question: do we replace or remove? We could replace with a "Too late to add to cart" message. However this might be a lot of content and maybe the cart state can explain this.

### PR DESCRIPTION
**Pull request by ryancreatescopy**
Need to test....

- [x] @samajammin look into getter logic to confirm they're working
- [ ] Hook up projectlistCard to matching pool contribution when we display message about project contributions being over... (search for a todo in the code)

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Need some help getting this to work/testing @samajammin

**Comment by samajammin** [comment]
@ryancreatescopy what issue does this PR intend to solve? Or could you please describe what the goal is of this PR?

**Comment by ryancreatescopy** [comment]
Main goal of this is to update message in the first card of the projectList. We don't want to tell users to get prepared once the round is over for contributions etc... I believe it was also addressing issues around buttons on the projectListItem #74 / #75 – although I believe they've probably already been addressed elsewhere...

**Comment by samajammin** [comment]
@ryancreatescopy cool. I've made some updates to that logic on which CTA cards to display in the project list. Please take a look tomorrow & LMK if this achieves what you were looking for.

**Comment by ryancreatescopy** [comment]
When I got to update this branch locally I get a lot of scary conflicts, can we check this one together please?

**Comment by ryancreatescopy** [comment]
Looking good!


image

If `UserCanReallocate` they shouldnt see the "get prepared" card. I imagine we would use a getter that fetches data about their verification status (isRegistered) to define whether that card shows or not. 

The "open cart" button should probably only be visible if the cart is closed, otherwise it closes the cart.

**Comment by ryancreatescopy** [comment]
If the user has contributed, they should also see a card after reallocation that says that the round is over. Atm they don't get a card at all.

**Comment by ryancreatescopy** [comment]
Also, perhaps the round over card shouldn't have a hover transform state as there is no action – maybe we should apply this to all cards as only the button triggers the action anyway...

**Review by samajammin — APPROVED** [review]

**Pull request merged**
