### PR TITLE
Criteria modal fix

### PR DESCRIPTION
**Pull request by ryancreatescopy**
[wip] aligning round criteria modal with other modal styles (wallet/cart)

need help fixing it. I think something about `JoinLanding` is preventing it from rendering...

### CODE REVIEW

**Comment by samajammin** [comment]
@ryancreatescopy looks like you'd appreciate some help with the lingering todos here?

**Comment by wackerow** [comment]
Leaving as draft with one remaining blocker:
- [ ] Need copy for the "Honest and credible"  bullet

**Comment by samajammin** [comment]
@wackerow I appreciate that but I don't think the copy needs to be a blocker on this PR.

**Comment by ryancreatescopy** [comment]
I think it might be worth keeping open or at least creating a new notion ticket to address this.

**Review by samajammin — CHANGES_REQUESTED** [review]
@wackerow this LGTM on my XL screen but we should make the modal scrollable for smaller screens - the lower content currently gets cut off: https://share.getcloudapp.com/2NuwDD1R

**Comment by samajammin** [comment]
Scroll functionality looks good on mobile but smaller desktop still doesn't work.

@wackerow could you please look into polishing this up?

**Comment by wackerow** [comment]
image
Noticing this since recent changes

**Review by samajammin — APPROVED** [review]
👍

**Pull request merged**
