### PR TITLE
"Optimism balances" needs updating

### LINKED ISSUE #258: "Optimism balances" needs updating
image

- [ ] Needs to be switched to "Arbitrum balances"
- [ ] ℹ Needs some copy in a tooltip

### PR DESCRIPTION
**Pull request by corwintines**
Fixes: https://github.com/ethereum/clrfund/issues/258

**What Changed**
- Switch logos and copy from Optimism to Arbitrum

### CODE REVIEW

**Review by wackerow — COMMENTED** [review]
Wondering if it's worth incorporating some of this into `src/plugins/Web3/constants/chains.ts` to make things more dynamic.

We already store the names of each chain as `label`, and to make this less hard-coded and more flexible we could pull this label name and use here. We could also potentially add to the `chains.ts` file with logo filenames and background colors. 

This could enable potentially deploying this on a different network in the future without having to refactor anything. Curious what others think here

**Comment by corwintines** [comment]
Im not against it, would certainly make it a bit more dynamic in that sense. Ill play with it and see what I come up with.

**Comment by corwintines** [comment]
@wackerow added changes for this in.

**Review by samajammin — APPROVED** [review]
Nice 👍

**Pull request merged**
