### PR TITLE
Build better breadcrumbs

### PR DESCRIPTION
**Pull request by corwintines**
Implement breadcrumbs

### CODE REVIEW

**Review by samajammin — CHANGES_REQUESTED** [review]
Looks great! A couple requests...

1) mobile wrapping:
Image 2021-12-14 at 5 37 36 PM
Can we ensure they stack vertically if they must wrap?
e.g.
ABOUT /
HOW-IT-WORKS /
CONTRIBUTORS /

2) project detail page
- displaying the full hash looks a bit ugly, can we just hide this (since the link is self-referential anyway)?
- Can we display "projects" instead of "projects" since it links back to the projects page?
Image 2021-12-14 at 5 38 24 PM

**Comment by pettinarip** [comment]
> displaying the full hash looks a bit ugly, can we just hide this (since the link is self-referential anyway)?

We can display the name of the project instead. e.g. "PROJECTS / THE AWESOME PROJECT"...not sure if this is doable, or easy to implement. If not, Im ok with just leaving PROJECTS

**Review by pettinarip — COMMENTED** [review]
The `/verify` and `/transaction-success` pages need a bit of space adjustment.

image
image

**Comment by samajammin** [comment]
@corwintines converting this to draft. LMK when it's ready for review.

**Comment by corwintines** [comment]
@samajammin should be good to go now

**Review by samajammin — CHANGES_REQUESTED** [review]
Looks good! Except the issues on some of the tx success routes (/join & /verify) still have issues.

e.g. here it's above the banner & there's no margin/padding:
Image 2022-01-10 at 11 18 18 AM

e.g.
- https://deploy-preview-477--eth2clrfund.netlify.app/#/join/success/0x4aa98910fe8ffe91c18dae4248193f8501f6194a3c36cbafbc95522743abab79
- https://deploy-preview-477--eth2clrfund.netlify.app/#/verify/success/0x4aa98910fe8ffe91c18dae4248193f8501f6194a3c36cbafbc95522743abab79

**Review by samajammin — APPROVED** [review]
Nice!

**Pull request merged**
