### PR TITLE
Landing page layout bug after JoinPhase

### PR DESCRIPTION
**Pull request by corwintines**
https://github.com/ethereum/clrfund/issues/125

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
On large screens we still cut off some of the image. Is there a way we can maybe shrink the image so that more of it is in focus? Also, without the Join banner should we make the text more central in this area? At the moment it sits quite high up in the hero area.

image

**Comment by wackerow** [comment]
Should we consider a max-width on this section? To your point @ryancreatescopy, as the screen width gets larger, the height really doesn't, so the image gets bigger and bigger, cutting off more of it vertically. If we cap the width of this section at maybe the `$breakpoint-l` (1200px) mark, that should keep it readable and prevent the image from getting larger. 
cc: @corwintines

**Comment by corwintines** [comment]
@ryancreatescopy @wackerow added some changes to the comments. Let me know what you think.

**Review by ryancreatescopy — APPROVED** [review]
Looks awesome. Thanks @corwintines

**Pull request merged**
