### PR TITLE
Images not displaying correctly after IPFS upload

### LINKED ISSUE #243: Uploaded images during Join form not displaying correctly
We request that users use files that are specific aspect ratios, but the images are not being scaled appropraitely.

image

- Would expect the banner image to fill it's width, and clip vertically if too tall.
- Same with thumbnail, the horizontal width should always match it's parent, then maintain aspect ratio as it scales.

### PR DESCRIPTION
**Pull request by corwintines**
Fixes: https://github.com/ethereum/clrfund/issues/243

**What changed**
- Added width and height metadata to svg so that it can be rendered properly

### CODE REVIEW

**Review by pettinarip — APPROVED** [review]
Looks good!

The only aspect to mention is in the Project view. Shouldn't we keep it as `cover` in that case? I have the feeling that covering the full space with the image is a design requirement. Also since we are warning the user about the sizes of the banner image `Recommended aspect ratio: 16x9`.

image

**Comment by corwintines** [comment]
I am definitely down to change to cover if we want!

**Review by samajammin — CHANGES_REQUESTED** [review]
Agree with @pettinarip - the profile page should be `cover` to take up full width.

Otherwise LGTM!

**Comment by wackerow** [comment]
Yes, agreed. @corwintines If you update this for `IpfsImageUpload` make sure to also update `ProjectProfile.vue` (class `.project-image`) as well so the same styling applies when the project is displayed. Looking great! Thanks for fixing this up =)

**Review by samajammin — APPROVED** [review]

**Pull request merged**
