### PR TITLE
Lambda functions - domains whitelist

### PR DESCRIPTION
**Pull request by pettinarip**
Added a domain whitelist to allow calls to the lambda functions.

### CODE REVIEW

**Comment by samajammin** [comment]
@pettinarip nice!

This reminds me - can you please create issues/PRs for this same feature in other repos where we use lambda functions?
- https://github.com/ethereum/ethereum-org-website
- https://github.com/ethereum/esp-website

**Comment by pettinarip** [comment]
@samajammin yes!

**Comment by pettinarip** [comment]
@samajammin wondering what you think about the next:

I was thinking about subdomains. Do you think it's worth adding a broader check? like adding a regex to check not only the host but also its subdomains.

If we don't have too many of these cases we could just add all the cases in the array and it's done
```js
LAMBDA_DOMAIN_WHITELIST=['host', 'subdomain1.host', 'subdomain2.host', ...]
```

But maybe if we have dynamic subdomains (like the Netlify preview deploys), we should consider a regex.

**Comment by samajammin** [comment]
@pettinarip ya I'm not too worried about limiting access to specific subdomains, at least not yet.

Sounds like you're now going the CORS route - should I hold off from reviewing/merging this?

**Comment by pettinarip** [comment]
@samajammin Yes, I'll change it to Draft so that we don't make any mistake while I test the CORS solution I think is a much more robust one.

**Comment by samajammin** [comment]
@pettinarip I'm going to close this out for now. Feel free to re-open if we decide to address this.

**Pull request closed without merging**
