### PR TITLE
Add recipient transaction on form submission

### PR DESCRIPTION
**Pull request by samajammin**

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Design notes:
- We should probably dd an overlay once the tx begins so the user doesn't try to edit the form.
- Need to fix logic of when to replace progress steps with tx status – this should only happen if the user submits the tx
image
The above should never happen
`<div class="tx-progress-area" v-if="currentStep === 5 && pending || waiting || txReject || wrongNetwork || lowFunds">` doesn't appear to be working

**Comment by ryancreatescopy** [comment]
I just want to document some behaviour that probably isn't clear...

When a user lands on the review page on mobile they should see something like this:

image

The "Finish" CTA is essentially saying "I'm happy with the info provided" and this should trigger the transaction information appearing, e.g.:

image

Note: in this screenshot the user isn't connected so the main CTA is to connect the wallet. Once that is done, they will see something like this:

image

One the user hits "submit project" that should trigger the tx and they'll get a state like this:

image

The area above the receipt will cover the various tx states and we'll need to disable the CTA to indicate that actions are expected in the wallet and/or happening. We don't want duplicate TXs being sent.

---

The reason we stagger the display of this is because it takes up way too much vertical height on mobile and will make reviewing the form difficult to start with.

I think we also should put an overlay underneath the transaction modal once the user hits that original "Finish" CTA so the user doesn't try to edit anything in the form.

One thing we still need to consider is what to do with the "Previous" button... it should probably change to something like minimise, but we should encourage the user to stay here so they get the tx information like pending and success. Hopfully on L2 this would be quick anyway so we could remove the button altogether!

---

On desktop this will work slightly differently. Because we have more space, we don't need that interstitial "Finish" step. Instead we can display the transaction summary as soon as the user gets to the summary page (bear in mind this would be the "Connect" CTA if they were not yet connected...

image

However, once the user commits to this tx, we can use the progress area for displaying tx status, e.g.

image

Again, maybe at this point we remove the "Previous" button too.

---

Anywho, just thought it'd be useful to jot down these points for async work...

**Comment by samajammin** [comment]
@ryancreatescopy re: some of your comments

> - We should probably dd an overlay once the tx begins so the user doesn't try to edit the form.
> - Need to fix logic of when to replace progress steps with tx status – this should only happen if the user submits the tx
> - On desktop this will work slightly differently. Because we have more space, we don't need that interstitial "Finish" step.
> - Again, maybe at this point we remove the "Previous" button too.

The more I think about it, I think it might be best to have a clear transaction step/state (no real preference whether that's a modal or another route) given the aspects of logic you mention - we don't want the user trying to edit the form, we no longer want to display a list of steps with links to each. Particularly when they're in between various txs. Let's chat through this tomorrow.

**Comment by samajammin** [comment]
@ryancreatescopy @wackerow still work to be done here but I got a happy path flow working that I'd like to review with you tomorrow.

I ended up adding an additional "submit" step to this recipient flow. It made it easier to break out the transaction logic. Happy to chat through alternatives here.

**Comment by samajammin** [comment]
@ryancreatescopy @wackerow - got the basic functionality working. I'm going to merge this in given the significant component changes.

**Pull request merged**
