### PR TITLE
IPFS upload refactor

### PR DESCRIPTION
**Pull request by samajammin**
- Style updates to IPFS section
- Adds optionality to manually input an IPFS hash

Waiting to hear back from the TG group re: using an API service to pin the images for us.

In the meantime, Infura claims to pin images for 6 months:
https://blog.infura.io/an-introduction-to-ipfs/
> So, how do you pin your data across the IPFS network via the Infura API? It’s much easier than you think! Once you have an Infura account (you can sign up for one here), you will be able to upload your file to IPFS and access that data. Data is currently pinned until it’s been 6 months since it was last used, so as long as you’re accessing your data within that time frame, it’ll be there for you!

So I think it's worth a try to keep this feature. If we find ourselves with issues during a funding round, we'll still have the IPFS hashes on the smart contract, so I belive we can pin them ourselves with an IPFS node if absolutely necessary.

### CODE REVIEW

**Comment by ryancreatescopy** [comment]
Dropping some thoughts/feedback:

image

We should update the description, e.g. "We'll upload your images to IPFS, a decentralized storage platform." – I need clarification on this new process but essentially the user can either upload or just paste a hash?

Should we include a link to somewhere they can upload their image to receive a hash? I guess why would they ever do this if we have an upload right there...

image

- Banner image input label should have same styling as the hash input label
- Any ideas on the best way to find out the optimum image size? 
- File input should have same rounded corners
- Should we put a separator between the file input and hash input  with like `OR` to show optionality, looks like both fields might be needed?

image

- if the image doesn't load, the remove button looks weird, perhaps we re-work this? Or is there a fallback we should consider?
- Maybe we can actually get rid of the dark div that houses the image and the remove button and move the "remove" button to the bottom
- if this happens is there a way that a user could look up the hash and see if it renders with a different service? Does that actually help anything?

image

- Should "remove" also remove selected file from "choose file" input?

---

Maybe let's chat through this all at pairing.

**Comment by samajammin** [comment]
@ryancreatescopy thanks for the feedback!

@ryancreatescopy @wackerow as we discussed, I've removed the hash inputs for now, given that we're confidence the Infura upload approach via `ipfs-mini` works.

> Any ideas on the best way to find out the optimum image size?

As in the file size? Seems we already include recommend dimensions, ya?
I think a general rule of thumb could be to keep the size below 400 kb.

> if the image doesn't load, the remove button looks weird, perhaps we re-work this? Or is there a fallback we should consider?

Interesting... I haven't been able to replicate this but that sounds like a bug 🤔 . Do you know if there was a console error when this occurred? Ideally we identify when this happens & perhaps have the user re-upload the image.

> Maybe we can actually get rid of the dark div that houses the image and the remove button and move the "remove" button to the bottom

I think this makes sense. Remove button hovering in the center of that div seems like a weird layout IMO. Maybe we just have a "remove image" link next to the IPFS hash? Similar to the "cancel" link in the form? Something like:
Image 2021-05-09 at 3 15 46 PM

> if this happens is there a way that a user could look up the hash and see if it renders with a different service? Does that actually help anything?

We could potentially provide an external link to their image, e.g. https://ipfs.io/ipfs/QmdhKa6jdeEAq3qqaD2y9pys7NhRcAabVLicqcr3ixnqK2

> Should "remove" also remove selected file from "choose file" input?

Yes but I couldn't figure out how to do this without TypeScript throwing a fit 😠

**Comment by ryancreatescopy** [comment]
> As in the file size? Seems we already include recommend dimensions, ya?

Yes, but they're just placeholder. I mean the dimensions.

**Comment by ryancreatescopy** [comment]
Made some tweaks. I think the image isn't loading properly, seems to load at full size rather than fitting the container. Perhaps this is something we could look at.

last touches:

- [x] Adding "copied!" state to the copy button (this is something that's needed in quite a few places: component?
- [x] Add image size advice

**Pull request merged**
