### PR TITLE
Dark background behind hero text

### LINKED ISSUE #137: Dark background behind hero text
image

On mobile, the becomes quite unreadable against the backdrop. I suggest we add a dark bg with a low opacity to ensure the text remains readable.

### PR DESCRIPTION
**Pull request by corwintines**
Fixes: https://github.com/ethereum/clrfund/issues/137

### CODE REVIEW

**Comment by pettinarip** [comment]
In the preview, I see this:
image
seems like the dark background is not filling the complete space

**Comment by corwintines** [comment]
@pettinarip trying to reproduce, mind letting me know what you did. Been trying to play around with responsive view and cant replicate.

**Comment by pettinarip** [comment]
@corwintines
1. Open the netlify preview deploy
2. Go into responsive view in developer tools
3. Start shrinking until you hit the md breakpoint, you will see the issue

I've tested it in chrome (incognito to avoid any cache) and ff. If you can't reproduce it I could share my screen if necessary.

**Comment by corwintines** [comment]
Oh I see now! happens when the call to action is no longer there. Thanks!

**Review by pettinarip — APPROVED** [review]
Nice! its working good for me

**Review by wackerow — APPROVED** [review]
Lookin good!

**Pull request merged**
